version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/templates/py"
    schedule:
      interval: "semiannually"
    cooldown:
      default-days: 30
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/templates/ts"
    schedule:
      interval: "semiannually"
    cooldown:
      default-days: 30
    groups:
      npm-dependencies:
        patterns:
          - "*"
